# -*- coding: utf-8 -*-
"""sistema_de_auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_REclcN_vFt2zXRhTGm90cHatdtmLBe

# Sistema de Auditoria de Recursos Corporativos
> Diego Marques de Carvalho
"""

import time

# Decorator de auditoria
def auditor(func):

    def wrapper(*args, **kwargs):

        print("===== AUDITORIA =====")
        print("Iniciando cálculo...")
        print("Argumentos recebidos:", args)
        print("Parâmetros recebidos:", kwargs)

        inicio = time.time()

        resultado = func(*args, **kwargs)

        fim = time.time()

        print("Tempo de execução:", fim - inicio)
        print("===== FIM DA AUDITORIA =====\n")

        return resultado

    return wrapper


# Estrutura da empresa
empresa = {

    "Matriz": {

        "TI": {
            "Infraestrutura": 50000,
            "Desenvolvimento": 80000,
            "Suporte": 30000
        },

        "RH": {
            "Recrutamento": 20000,
            "Treinamento": 15000
        }
    },

    "Filial": {

        "Financeiro": {
            "Contabilidade": 40000,
            "Auditoria": 25000
        },

        "Comercial": {
            "Vendas": 60000,
            "Marketing": 35000
        }
    }
}


@auditor
def calcular_orcamento(dados, *args, **kwargs):

    total = 0

    # taxa de câmbio
    taxa = kwargs.get("taxa_cambio", 1)

    for chave, valor in dados.items():

        # Ignora departamentos
        if chave in args:
            continue

        # Verifica se é outro dicionário
        if type(valor) == dict:

            total += calcular_orcamento(valor, *args, **kwargs)

        else:
            total += valor

    return total * taxa


# Execução do programa
resultado = calcular_orcamento(
    empresa,
    "RH",                    # departamento ignorado
    moeda_destino="BRL",
    taxa_cambio=1
)

print("Orçamento total:", resultado)

def calcular_orcamento():